name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Create minimal content
        run: |
          WWWROOT_PATH=$GITHUB_WORKSPACE/wwwroot
          mkdir -p $WWWROOT_PATH
          echo "<html><body><h1>Test Page</h1></body></html>" > $WWWROOT_PATH/index.html
          echo "Files in wwwroot:"
          ls -la $WWWROOT_PATH

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: $GITHUB_WORKSPACE/wwwroot