name: Update Data and Deploy Site

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update download data
        run: npm run update-data

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update download counts data'
          file_pattern: 'data/download-counts.json'

      - name: Copy site files to output folder
        run: |
          mkdir -p public
          cp src/index.html public/
          cp data/download-counts.json public/

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: update-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
