name: Update and Deploy Site

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install

      - run: npm run update-data

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update download data"
          file_pattern: "data/download-counts.json"

      - name: Prepare site
        run: |
          mkdir -p public
          cp src/index.html public/
          cp data/download-counts.json public/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
